### PR TITLE
Added ALC271 layout-id 3 by Mirone (Tested on Acer Aspire v5-571PG)

### PR DESCRIPTION
**Pull request by kylon**

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Already present. It's ALC269 layout-id 31

**Comment by kylon** [comment]
This acer pc has no audio without this.

**Comment by vandroiy2013** [comment]
Inject layout 31

**Comment by kylon** [comment]
It is not fully working.
Audio in macOS is ok but other stuff are not working like the mic.

Maybe this is a different patch or something is missing in alc269

**Comment by vandroiy2013** [comment]
Try ALL provide layouts for ALC269. Your codec is ALC269! ALC271x is a marketing name...
Read WiKi to find out available layouts for ALC269...

**Pull request closed without merging**
