### PR TITLE
Update from original

### PR DESCRIPTION
**Pull request by insanelydeepak**
Update from original

### CODE REVIEW

**Comment by vit9696** [comment]
Thanks, but why deleting the revisions? I'd rather you recover them.
Also, could you please change your editor preferences to avoid making extra lines when editing plists? This creates extra lines in diffs and makes them [harder to read](https://github.com/vit9696/AppleALC/pull/76/files#diff-6d44613943f31005c5cdfefc15e63357L132). We prefer Apple-style plist formatting in the project.

**Comment by insanelydeepak** [comment]
please close this PR , im new to git and my fork behind  your commits , was trying to update from Master , i guess i did wrong

**Comment by vit9696** [comment]
Alright. You could use svn on github though. It is much less of a pain, although it is not food pull-requests.

**Comment by insanelydeepak** [comment]
@vit9696  thanks alot , will learn more

**Pull request closed without merging**
