### PR TITLE
New Updates for AppleALC

### PR DESCRIPTION
**Pull request by insanelydeepak**
Added all my Desktop Patches to AppleALC

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Please resolve conflicts and commit again. Thank you.

**Comment by vandroiy2013** [comment]
Also pay attention to changelog. New rules to add patches.

Sync layout names (1,2,3 - Toleda Desktop, 1-8 - Mirone Laptop, 5,7 - Mirone Desktop, 10-99 - Custom User layouts)
Sync platforms names (platformsT - Toleda, PlatformsM - Mirone, Platforms10-99 - custom user platforms)

Custom patches MUST be from 10 to 99.
1-10 reserved for Mirone/Toleda Basic patches. Use ALC269 resources as example. Thank you.

**Comment by insanelydeepak** [comment]
so you want me to rename all patches again ??

**Comment by insanelydeepak** [comment]
where's confliction  ??

**Comment by insanelydeepak** [comment]
what numbers will be reserved for me ??
i also want others won't replace my patches too , i also have lots of patches

**Comment by vandroiy2013** [comment]
Just updated WiKi https://github.com/vit9696/AppleALC/wiki/Adding-codec-support
You can take any free number from 10 to 99 .
Also don't add Mirone/Toleda resources as Custom resources under 11-99 layouts. Duplicates is not good too. I added ALC1150 Toleda 1, 2 and Mirone 5, 7 just for example. Both of this resources are equal  and can replace one another. So we should choose what resources we can reserve for project. Leaving them both is useless due to the kext size. Specially for those who use ozmosis.

We need order in resources to reduce size! Base codecs with base layouts/platforms and several custom resources for each codec. Thats all. For problem codecs like ALC269 now we have 11 (Eleven)!!! different versions. It's too much... Imagine 10-15 different resources for each codec. So try to understand quantity is not often good.

So choose carefully what you want to add... And you also can make your own version with ALL your resources. 
Thanks for understanding.

**Comment by insanelydeepak** [comment]
thats why i removed Mirone patched from my AIO repo , just added all mine patches so taking 10-20 for me laptop as well (Suggest me something better ), for reducing size I'm using one platform for all layouts isn't good ?? like in AppleHDA ??

**Comment by vit9696** [comment]
Well, this is a total mess no one could merge even in theory. At least because it is not rebased and basically breaks the existing resources.  

AppleALC tends to use generalised codec submissions from well known sources (toleda, Mirone, certain others), and custom ones when this is absolutely necessary. For example, a few laptop layouts.  
If one submits a codec addition it must comply with the wiki [guideline](https://github.com/vit9696/AppleALC/wiki/Adding-codec-support#rules-to-add-resources). Moreover, it is to be clear why a certain patch/layout is needed, and why do not the existing ones already cover the needs.

**Comment by insanelydeepak** [comment]
Yeah why I'm here hehehe , if custom layout will never needed then there's not my existence in AppleHDA Scene

**Comment by insanelydeepak** [comment]
Fixed as per rules

**Comment by vit9696** [comment]
Sorry, but I repeat that this cannot be merged. If you check the [diff](https://github.com/vit9696/AppleALC/pull/28/files) you will see a total mess you've made. You touched ALC1150, and many other codecs. Consider making a break and analysing what you want to do.  
Make a new pull request with only the relevant changes. Explain why each layout is absolutely needed.

**Comment by insanelydeepak** [comment]
Ok Thank you

**Pull request closed without merging**
