### PR TITLE
Realtek ALC662

### PR DESCRIPTION
**Pull request by insanelydeepak**
- Layout11 - InsanelyDeepak  8/9 ports (Grey,Black,Orange, Pink, Green,
Blue)
- Layout12 - InsanelyDeepak  5/6 ports (Orange, Pink, Green, Blue)
- Layout14 - InsanelyDeepak  5/6 ports (Orange, Pink, Green, Blue)
**Realtek ALC662 v2**
- Layout13 - InsanelyDeepak  5/6 ports (Orange, Pink, Green, Blue)

### CODE REVIEW

**Comment by insanelydeepak** [comment]
If there's issue still , then i think problem with PlistEditor i'm using

**Comment by vandroiy2013** [comment]
What is the difference between layouts 12, 13 and 14 in ALC662? 5/6 ports already exists in Mirone layout 7. Why your patches better? Why do we need 3 extra layouts with the same ports? Layout 11 is OK.
What is the difference between layouts 11 and 12 in ALC883? 5/6 ports already exists in Mirone layout 7. Why your patches better? Why do we need 2 extra layouts with the same ports? Layout 13 is OK.

As vit9696 told you yesterday - it is to be clear why a certain patch/layout is needed, and why do not the existing ones already cover the needs.

Thanks.

**Comment by insanelydeepak** [comment]
No i haven't said my patches are best than Mirone but fulfil requirement which they can't like ALC887 i have 4 layout one (11) which is only for AsusH61M-D and other three ports Mobo and other three won't works on my Mobo but for other they requested to make patches for them , Same story with ALC883 ,662 , 1150 and others .. i have alc668 12 version which for different laptop list is too big

**Comment by insanelydeepak** [comment]
Now i got your point just thinks to use Mirone and Toleda patches for all Desktop and Laptop ?? which is not  a good idea cuz they won't fulfill requirements for all but for some Example ALC269 series , there's flood around .. Thanks you i like your project cuz i was trying to make  i made which autdetect codec and install Patched AppleHDA , i was not a good coder .. i started support cuz i let people thinks their codec isn't supported

**Comment by insanelydeepak** [comment]
Suggestion 
you can make list supported list of codec with How many ports of hardware is supported using particular layoutID . will be a great for new comers Thanks you 

PS: plz remove P/R

**Comment by vit9696** [comment]
@insanelydeepak I do not understand what you mean. Probably because you come to conclusions without any attentive reading.  
In no way we are trying to use Mirone and Toleda patches for all the codecs. AppleALC incorporates lots of other configurations added by different people for their own hardware. What you do not understand is that these people **gave reasons** why certain configurations do not work for them, and why their configurations are necessary for their hardware.  
We do gladly accept the configurations from different users, but we do ask them to provide as much detail as possible. This way we will know that they can replace the existing configurations or live together.  
ALC269 is a very good example. There are numerous configurations specific to each laptop, which are completely different from the others. Clearly no generic variants will work for that.

**Comment by insanelydeepak** [comment]
will be no conflicting anymore whenever a P/R there will be more specific reasoning 
Thank you

**Comment by vit9696** [comment]
Alright :) We are counting on you. Thanks for your patience.

**Pull request closed without merging**
