### PR TITLE
Realtek ALC898 for MSI GS40

### PR DESCRIPTION
**Pull request by insanelydeepak**
its fully woking input and output for MSI GS40

### CODE REVIEW

**Comment by vit9696** [comment]
Hi,
Looking at the diff I noticed that...
* some ALC 887 layouts were removed: 12, 13, 17 → 13, 17, 18. Is that intentional? Could you give us anything for the changelog?
* there are many plist formatting changes like `<data>QcYGAEmLvCQ=</data>` becoming 
```
<data>
QcYGAEmLvCQ=
</data>
```
could this be fixed?

Thanks

**Comment by insanelydeepak** [comment]
1. yes this intentionally , i was optimizing ALC887 list (user's reported some of layout(like 12) not working) so i fixed it 
2. 
`<data>
QcYGAEmLvCQ=
</data>
`
don't how this happen i used Plisteditorpro , let me try with Xcode 

PS : CS4210 as i told unable to find why Bin-patch not working , but yes it's working fully with Clover Patches and AppleALC 
also did some correction to codec resource will do P/R soon

**Comment by insanelydeepak** [comment]
corrected :)

**Comment by insanelydeepak** [comment]
should i do P/R Again ?

**Comment by insanelydeepak** [comment]
👍 
Thank you :)

**Comment by vit9696** [comment]
>PS : CS4210 as i told unable to find why Bin-patch not working , but yes it's working fully with Clover Patches and AppleALC 
also did some correction to codec resource will do P/R soon
Did you check the patches themselves? Values… counts, etc?
>should i do P/R Again ?
No, that's ok as it is I guess. Just need to update the changelog later.

**Comment by insanelydeepak** [comment]
> Did you check the patches themselves? Values… counts, etc?
yes patches were exact , compared with other codec patches too , they are good i guess 
i will recall test and try to fix asap

**Pull request merged**
