### PR TITLE
Add ALC225/ALC3253 on dell ins 7579

### PR DESCRIPTION
**Pull request by ChalesYu**
Tested on my dell inspiron 15MF 7579
layouid is 3 and 28

headphone need CodecCommander to get sound
P.S.  layout-id 28 is copy from ALC295 files ,but it can work

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi. I can't merge this until you clarify origin of this resources. First of all you can't use same platformsM.xml.zlib for @Mirone resources and for custom resources. If layout 3 was made by @Mirone you should separate it from layout 28 and specify it in Comment line (Mirone - ALC225). Also make separate platforms28.xml.zlib for layout28. And also need clarification why we need two different layouts for one notebook. What differences in this layouts? Thanks

**Comment by ChalesYu** [comment]
uh , Yes ,  I'll send a new Pull requests about this 
And I think layout 28 is works better than layout 3

**Comment by vandroiy2013** [comment]
Then provide ONLY layout 28. And when @Mirone updates his AppleHDAPatcher with support of this codec i'll add resources from his official repo.

**Comment by ChalesYu** [comment]
#152  updated

I Will reply on next morning ,  Too sleepy

**Pull request closed without merging**
