### PR TITLE
ALC888 InsanelyDeepak

### PR DESCRIPTION
**Pull request by insanelydeepak**
initial Support

### CODE REVIEW

**Comment by insanelydeepak** [comment]
Layout_ID = 11 AC'97 front panel support ( 3 ports) 
Layout_ID = 12  3 ports all working tested

**Comment by insanelydeepak** [comment]
Layout_ID = 11 AC'97 front panel support ( 3 ports) 
Layout_ID = 12  3 ports all working tested

**Comment by insanelydeepak** [comment]
Layout_ID = 11 AC'97 front panel support ( 3 ports) 
Layout_ID = 12  3 ports all working tested

**Comment by vandroiy2013** [comment]
I can't merge this PR. 3 ports already exists. Layout-id 5. AC97 is not needed for 99% of users... As i told you before - size matters. Sorry... In case for ALC887 there were optimizations to existent data.

**Pull request closed without merging**
