### PR TITLE
RealtekALC887-VD by InsanelyDeepak

### PR DESCRIPTION
**Pull request by insanelydeepak**
- Layout_ID 11 = ​​3 ports supported (Pink, Green, Blue, CodecAddress:
2, Disable Auto-Switch : you have to manually switch between Speakers
and Headphones) AC97 Front Panel Headphone Support
- Layout_ID 12 = ​​3/4 ports supported (Pink, Green, Black, Orange,
CodecAddress: 2)
- Layout_ID 13 = ​​5/6 ports supported (Pink, Green, Black, Blue,
Orange, CodecAddress: 2
- Layout_ID 14 = ​​3/4 ports supported (Pink, Green, Blue, Orange,
CodecAddress: 0)
- Layout_ID 15 = 5/6 ports supported (Pink, Green, Blue, Orange,
CodecAddress: 0)

### CODE REVIEW

**Comment by vit9696** [comment]
@vandroiy2013 I guess this is safe to merge?

**Comment by vandroiy2013** [comment]
@vit9696 Why not... Let's try this layouts on applelife. They have some problems with this codec..

**Comment by insanelydeepak** [comment]
Yes this is fool proof , cuz i was noob to use git , now add it and new codecs are coming ALC662 and A665

**Comment by vit9696** [comment]
Thanks

**Comment by insanelydeepak** [comment]
if you have some tips plz provid me 

Thank you Guys

**Pull request merged**
